use openeyes;

-- Clear out duplicate macros and tidy up
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='1';
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='2';
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='3';
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='4';
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='5';
DELETE FROM `ophcocorrespondence_letter_macro_version` WHERE `version_id`='6';

UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='3';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='4';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='5';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='6';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='7';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='8';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='9';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='10';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='11';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='12';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='13';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='14';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='15';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='16';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='17';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='18';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='19';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='20';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='23';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='24';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='25';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='26';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='27';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='28';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='29';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='30';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='31';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='32';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='33';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='34';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='35';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='36';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='37';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='38';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='39';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='40';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='41';
UPDATE `ophcocorrespondence_letter_macro` SET `id`='25' WHERE `id`='42';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='44';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='45';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='46';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='47';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='48';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='49';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='50';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='51';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='52';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='53';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='54';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='55';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='56';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='57';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='58';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='59';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='60';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='61';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='63';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='64';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='65';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='66';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='67';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='68';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='69';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='70';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='71';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='72';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='73';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='74';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='75';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='76';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='77';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='78';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='79';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='80';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='81';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='83';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='84';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='85';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='86';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='87';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='88';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='89';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='90';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='91';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='92';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='93';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='94';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='95';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='96';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='97';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='98';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='99';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='100';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='101';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='103';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='104';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='105';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='106';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='107';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='108';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='109';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='110';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='111';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='112';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='113';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='114';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='115';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='116';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='117';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='118';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='119';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='120';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='121';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='122';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='123';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='124';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='125';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='126';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='127';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='128';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='129';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='130';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='131';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='132';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='133';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='134';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='135';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='136';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='137';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='138';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='139';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='160';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='161';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='162';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='163';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='164';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='165';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='166';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='167';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='168';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='169';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='170';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='171';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='172';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='173';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='174';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='175';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='176';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='177';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='21';

DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='193';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='194';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='196';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='43';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='187';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='188';
UPDATE `ophcocorrespondence_letter_macro` SET `id`='' WHERE `id`='297';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='300';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='213';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='214';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='294';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='226';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='225';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='245';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='246';
UPDATE `ophcocorrespondence_letter_macro` SET `name`='DR- DNA' WHERE `id`='227';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='293';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='190';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='189';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='62';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='64';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='63';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='22';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='185';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='259';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='260';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='257';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='258';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='254';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='255';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='292';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='270';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='271';
UPDATE `ophcocorrespondence_letter_macro` SET `subspecialty_id`=NULL, `site_id`='3' WHERE `id`='215';
UPDATE `ophcocorrespondence_letter_macro` SET `name`='Listed for 1st eye', `letter_type_id`='1' WHERE `id`='298';
UPDATE `ophcocorrespondence_letter_macro` SET `name`='Listed for 2nd eye', `letter_type_id`='1' WHERE `id`='299';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='282';
UPDATE `ophcocorrespondence_letter_macro` SET `name`='LVC- New' WHERE `id`='295';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='3' WHERE `id`='142';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='4' WHERE `id`='143';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='144';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='145';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='146';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='147';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='148';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='149';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='150';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='151';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='152';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='153';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='154';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='155';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='156';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='157';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='158';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='197';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='198';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='141';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='220';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='231';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='223';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='221';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='222';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`='1' WHERE `id`='286';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='232';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='229';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='191';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='192';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='262';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='265';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='263';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='267';
UPDATE `ophcocorrespondence_letter_macro` SET `site_id`=NULL WHERE `id`='266';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='199';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='200';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='183';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='184';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='211';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='224';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='296';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='289';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='247';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='248';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='253';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='252';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='290';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='234';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='303';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='301';
UPDATE `ophcocorrespondence_letter_macro` SET `body`='This [age] year old [sub] was discharged from hospital today.\n\nDIAGNOSIS: \n[epd]\n\nPROCEDURES: \n[opr]\n\nMEDICATIONS PRESCRIBED:\n[pre].\n\nALLERGIES:\n[alg]\n\nThe patient has been advised of the importance of taking their topical medication. [Pro] has been given an appointment for post-operative review in the coming weeks.' WHERE `id`='2';
UPDATE `ophcocorrespondence_letter_macro` SET `body`='This [age] year old [sub] was discharged from hospital today.\n\nDIAGNOSIS: \n[epd]\n\nPROCEDURES: \n[opr]\n\nMEDICATIONS PRESCRIBED:\n[pre].\n\nALLERGIES:\n[alg]\n\nThe patient has been advised of the importance of taking their topical medication. [Pro] has been given an appointment for post-operative review in the coming weeks.' WHERE `id`='4';
UPDATE `ophcocorrespondence_letter_macro` SET `body`='This [age] year old [sub] was discharged from hospital today.\n\nDIAGNOSIS: \n[epd]\n\nPROCEDURES: \n[opr]\n\nMEDICATIONS PRESCRIBED:\n[pre].\n\nALLERGIES:\n[alg]\n\nThe patient has been advised of the importance of taking their topical medication. [Pro] has been given an appointment for post-operative review in the coming weeks.' WHERE `id`='3';

UPDATE `ophcocorrespondence_letter_macro` SET `name`='Community Optom', `firm_id`=NULL, `letter_type_id`='4', `body`='Dear [pna]\n\nThe following information tells you about the arrangements for your aftercare.\n\nThe next check-up on your eye will be carried out by an optometrist (optician) in their practice. They will send a report back to the hospital and will issue a prescription for glasses if they are required.\n\nAn appointment to see an optometrist has been at the following time and place:\n\n\n_____________________________________________________________________________\n \n\nPlease take this letter with you to the appointment as it contains information the optometrist will need to complete your examination.\n\n\nTO THE OPTOMETRIST\n======================================================\n\n[Pna] UNDERWENT THE FOLLOWING PROCEDURE(S) and now requires a follow up examination:\n\n[opr].\n\nIOL LENS DETAILS: [ilt] with a power of [ilp]\n\nPOST OP TARGET REFRACTION ([loe] eye): [rxp]\n\nPRE-OP VA:\n[pov] \n\nPRE-OP REFRACTION:\n[por]\n\nIMPORTANT:\n--------------------\nWe would be grateful if you could supply outcome details for [Pnt] [Pnl] via our online portal, by visiting\n\nhttps://oegateway.org.uk/ \n\nThis allows for accurate outcome reporting to the National Cataract Audit being undertaken by the Royal College of Ophthalmologists.\n\nYou will need your GOC number, the patient\'s date of birth and the Unique Patient Reference below: \n               -------------------------\n                [puc]. \n               -------------------------\n\n\nFULL DETAILS OF THE PERFORMED PROCEDURES(s): \n----------------------------------------\n[opv].\n----------------------------------------\n\nCURRENT OPHTHALMIC DIAGNOSES:\n[aod]\n\nNo further hospital eye service appointments have been organised. If there are any concerns about the patient please contact us.\n' WHERE `id`='270';

DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='268';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='288';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='275';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='274';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='241';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='216';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='219';
DELETE FROM `ophcocorrespondence_letter_macro` WHERE `id`='302';
UPDATE `ophcocorrespondence_letter_macro` SET `name`='Dry AMD' WHERE `id`='276';

-- Set letter types
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='235';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='236';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='237';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='230';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='102';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='104';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='103';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='195';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='196';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='25';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='45';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='44';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='0';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='238';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='239';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='240';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='291';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='277';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='242';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='243';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='244';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='2' WHERE `id`='269';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='278';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='217';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='218';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='279';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='272';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='227';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='186';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='24';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='23';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='276';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='280';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='295';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='273';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='215';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='140';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='142';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='143';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='231';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='223';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='220';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='221';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='222';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='286';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='229';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='232';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='82';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='84';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='83';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='267';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='265';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='263';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='266';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='159';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='161';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='160';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='2' WHERE `id`='2';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='2' WHERE `id`='4';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='2' WHERE `id`='3';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='249';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='3' WHERE `id`='228';
UPDATE `ophcocorrespondence_letter_macro` SET `letter_type_id`='1' WHERE `id`='285';


-- Clean letter snippets
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='62';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='63';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='64';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='65';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='66';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='67';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='68';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='69';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='70';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='71';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='72';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='73';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='74';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='75';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='76';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='77';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='78';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='79';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='80';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='548';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='549';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='503';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='505';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='507';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='509';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='511';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='513';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='515';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='517';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='519';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='521';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='523';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='525';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='527';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='529';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='531';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='533';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='535';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='537';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='539';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='592';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='593';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='426';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='430';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='434';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='438';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='442';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='446';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='450';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='454';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='458';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='462';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='466';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='470';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='474';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='478';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='482';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='486';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='490';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='494';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='498';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='586';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='587';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='102';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='103';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='104';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='105';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='106';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='107';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='108';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='109';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='110';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='111';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='112';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='113';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='114';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='115';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='116';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='117';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='118';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='119';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='120';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='552';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='553';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='182';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='183';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='184';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='185';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='186';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='187';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='188';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='189';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='190';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='191';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='192';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='193';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='194';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='195';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='196';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='197';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='198';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='199';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='200';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='560';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='561';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='402';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='403';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='404';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='405';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='406';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='407';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='408';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='409';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='410';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='411';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='412';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='413';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='414';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='415';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='416';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='417';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='418';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='419';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='420';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='582';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='583';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='22';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='23';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='24';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='25';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='26';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='27';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='28';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='29';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='30';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='31';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='32';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='33';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='34';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='35';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='36';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='37';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='38';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='39';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='40';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='544';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='545';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='504';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='506';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='508';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='510';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='512';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='514';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='516';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='518';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='520';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='522';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='524';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='526';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='528';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='530';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='532';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='534';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='536';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='538';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='540';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='594';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='595';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='427';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='431';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='435';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='439';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='443';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='447';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='451';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='455';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='459';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='463';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='467';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='471';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='475';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='479';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='483';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='487';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='491';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='495';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='499';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='588';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='589';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='162';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='163';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='164';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='165';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='166';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='167';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='168';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='169';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='170';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='171';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='172';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='173';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='174';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='175';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='176';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='177';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='178';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='179';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='180';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='558';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='559';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='144';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='145';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='146';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='147';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='148';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='149';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='150';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='151';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='152';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='153';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='154';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='155';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='156';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='157';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='158';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='159';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='160';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='556';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='557';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='142';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='143';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='202';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='203';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='204';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='205';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='206';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='207';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='208';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='209';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='210';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='211';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='212';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='213';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='214';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='215';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='216';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='217';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='218';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='219';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='220';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='562';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='563';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='242';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='243';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='244';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='245';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='246';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='247';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='248';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='249';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='250';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='251';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='252';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='253';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='254';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='255';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='256';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='257';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='258';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='259';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='260';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='566';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='567';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='342';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='343';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='344';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='345';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='346';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='347';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='348';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='349';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='350';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='351';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='352';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='353';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='354';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='355';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='356';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='357';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='358';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='359';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='360';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='576';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='577';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='428';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='432';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='436';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='440';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='444';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='448';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='452';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='456';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='460';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='464';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='468';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='472';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='476';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='480';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='484';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='488';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='492';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='496';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='500';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='590';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='591';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='282';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='283';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='284';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='285';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='286';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='287';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='288';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='289';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='290';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='291';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='292';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='293';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='294';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='295';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='296';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='297';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='298';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='299';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='300';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='570';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='571';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='82';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='83';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='84';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='85';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='86';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='87';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='88';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='89';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='90';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='91';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='92';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='93';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='94';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='95';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='96';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='97';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='98';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='99';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='100';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='550';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='551';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='262';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='263';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='264';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='265';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='266';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='267';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='268';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='269';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='270';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='271';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='272';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='273';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='274';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='275';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='276';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='277';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='278';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='279';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='280';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='568';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='569';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='2';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='3';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='4';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='5';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='6';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='7';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='8';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='9';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='10';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='11';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='12';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='13';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='14';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='15';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='16';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='17';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='18';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='19';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='20';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='542';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='543';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='361';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='362';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='363';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='364';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='365';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='366';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='367';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='368';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='369';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='370';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='371';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='372';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='373';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='374';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='375';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='376';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='377';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='378';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='379';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='380';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='578';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='579';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='42';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='43';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='44';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='45';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='46';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='47';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='48';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='49';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='50';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='51';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='52';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='53';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='54';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='55';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='56';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='57';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='58';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='59';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='60';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='546';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='547';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='596';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='597';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='302';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='303';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='304';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='305';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='306';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='307';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='308';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='309';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='310';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='311';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='312';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='313';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='314';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='315';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='316';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='317';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='318';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='319';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='320';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='572';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='573';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='121';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='123';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='124';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='125';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='126';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='127';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='128';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='129';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='130';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='131';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='132';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='133';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='134';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='135';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='136';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='137';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='138';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='139';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='140';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='554';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='555';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='322';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='323';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='324';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='325';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='326';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='327';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='328';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='329';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='330';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='331';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='332';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='333';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='334';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='335';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='336';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='337';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='338';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='339';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='340';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='574';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='575';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='222';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='223';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='224';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='225';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='226';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='227';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='228';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='229';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='230';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='231';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='232';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='233';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='234';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='235';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='236';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='237';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='238';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='239';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='240';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='564';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='565';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='382';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='383';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='384';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='385';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='386';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='387';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='388';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='389';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='390';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='391';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='392';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='393';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='394';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='395';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='396';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='397';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='398';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='399';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='400';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='580';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='581';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='3' WHERE `id`='425';
UPDATE `ophcocorrespondence_letter_string` SET `site_id`='4' WHERE `id`='429';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='433';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='437';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='441';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='445';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='449';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='453';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='457';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='461';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='465';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='469';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='473';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='477';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='481';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='485';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='489';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='493';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='497';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='584';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='585';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='598';
DELETE FROM `ophcocorrespondence_letter_string` WHERE `id`='599';
